### PR TITLE
Bug fixes for reducer, styles and state

### PR DESCRIPTION
**Pull request by 1makedadavis**

### CODE REVIEW

**Comment by Doomslair** [comment]
Hey, Makeda, I need to see a picture of how the front end looks after this pull request on here before I merge it, I also need to see a trello ticket waiting for review, with a picture associated with _it_ and a trello pr link to this pr.

**Comment by 1makedadavis** [comment]
[](url
Screen Shot 2021-11-09 at 12 37 27 PM
)

**Comment by Doomslair** [comment]
[Code-Cleanup](https://trello.com/c/bUUXbDds/118-code-cleanup)

**Review by Doomslair — APPROVED** [review]
Thank you so much! Looks great!

**Pull request merged**
