### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by 1makedadavis**

### CODE REVIEW

**Comment by Doomslair** [comment]
Did you make sure to merge main into your branch before pushing this up? Futhermore, what does the front end look like after this change?

**Comment by 1makedadavis** [comment]
Yes

**Comment by Doomslair** [comment]
Hey Makeda, looks like you missed my second question. Could you upload a photo to this pr for this to show what it looks like?

**Comment by 1makedadavis** [comment]
Ok. The pic is in the group channel. I’ll send now though

**Review by Doomslair — APPROVED** [review]
Looks good!

**Pull request merged**
