### PR TITLE
Implemented Reviews component with Review List rendering sample data, plus 1 unit test for rendering

### PR DESCRIPTION
**Pull request by apriljgranzow**

### CODE REVIEW

**Comment by apriljgranzow** [comment]
[Write unit test to check if review component is rendered](https://trello.com/c/KtIwGg2e/64-write-unit-test-to-check-if-review-component-is-rendered)

**Comment by apriljgranzow** [comment]
[Create reviews component](https://trello.com/c/Emtslhjf/65-create-reviews-component)

**Review by roheunji — APPROVED** [review]
Hey April, this looks good. I can follow the structure of your components.

**Comment by apriljgranzow** [comment]
[Render the first batch of reviews for an item](https://trello.com/c/CwNeSgz2/4-render-the-first-batch-of-reviews-for-an-item)

**Pull request merged**
