### PR TITLE
Related products

### PR DESCRIPTION
**Pull request by Doomslair**

### CODE REVIEW

**Review by apriljgranzow — COMMENTED** [review]
it looks 99% good but I'm concerned about the ESLint rules being disabled for [specific lines](https://github.com/FEC5-Fabaceae/project-catwalk/pull/37/files#diff-cafd0096923c420df625f52be7737b441d3be814c3f9ffaee3f47a759608abf5R13-R18), can you explain why you made those decisions?

**Comment by Doomslair** [comment]
> it looks 99% good but I'm concerned about the ESLint rules being disabled for [specific lines](https://github.com/FEC5-Fabaceae/project-catwalk/pull/37/files#diff-cafd0096923c420df625f52be7737b441d3be814c3f9ffaee3f47a759608abf5R13-R18), can you explain why you made those decisions? Also please attach a picture of what your component looks like to your PR

Super good question! I was trying to figure out how useState worked for hooks, and I wasn't using it appropriately. I just need to change that real quick

**Comment by Doomslair** [comment]
[Add Related-Product Cards](https://trello.com/c/K7ojSGc4/94-add-related-product-cards)

**Review by apriljgranzow — APPROVED** [review]

**Comment by Doomslair** [comment]
image

**Pull request merged**
