### PR TITLE
Questions&Answers MVP

### PR DESCRIPTION
**Pull request by roheunji**
@Doomslair

### CODE REVIEW

**Comment by roheunji** [comment]
[Individual Answer](https://trello.com/c/tdkuCqcX/71-individual-answer)

**Review by Doomslair — CHANGES_REQUESTED** [review]
Question and Answer contain cruft (code that is commented out). This needs to be removed before it can be merged.

Side note: Questions.test.js tests the Questions and Answers component. This is...confusing. Consider renaming Questions.test.js to QuestionAndAnswer.test.js

**Comment by apriljgranzow** [comment]
@roheunji Could you please attach a screenshot of what your component looks like currently?

**Comment by Doomslair** [comment]
> @roheunji Could you please attach a screenshot of what your component looks like currently?

She has it in her ticket

**Comment by apriljgranzow** [comment]
> > @roheunji Could you please attach a screenshot of what your component looks like currently?
> 
> She has it in her ticket

per Jonathan's slack announcement, we are to include a screen shot with all future pull requests if the PR alters the appearance in any way.

**Comment by roheunji** [comment]
Screenshot from 2021-11-01 13-12-32

**Review by Doomslair — APPROVED** [review]
Looks great!

**Pull request merged**
