### PR TITLE
Helpfulness feature and report feature with disabling

### PR DESCRIPTION
**Pull request by roheunji**
@Doomslair please review

### CODE REVIEW

**Comment by roheunji** [comment]
[Sending a report problem and helpful feature](https://trello.com/c/mkjsDsa1/78-sending-a-report-problem-and-helpful-feature)

**Review by Doomslair — CHANGES_REQUESTED** [review]
1. client/src/Components/Questions/AnswersList.jsx contains cruft that needs to be removed from commit at lines 7, 1-14
2. Have you verified these changes with a test (even if not included in a jest test) Is there any visible changes to the dom that I should see?

**Comment by roheunji** [comment]
I haven't made a test for it but it do see the increase in count when I click on the helpfulness counter and the answer is removed when I click report. The picture below shows the changes. The first picture
 is when it is first rendered. The second is when I click Yes for helpful and the last picture show when I click on report.
Screenshot from 2021-11-03 10-47-49
Screenshot from 2021-11-03 10-48-14
Screenshot from 2021-11-03 10-48-31

**Review by Doomslair — APPROVED** [review]
Alright, looks good!

**Pull request merged**
